persistence:
  createStorageClass: true
  defaultClass: true
  defaultClassReplicaCount: 2
  reclaimPolicy: Retain

defaultSettings:
  defaultDataPath: /home/k8s-storage

  # Don't allow creating a volume unless both replicas can exist
  defaultReplicaCount: 2
  allowVolumeCreationWithDegradedAvailability: false

  # Better scheduling on 2-node clusters
  replicaSoftAntiAffinity: false
  replicaDiskSoftAntiAffinity: false

  autoSalvage: true
  autoDeletePodWhenVolumeDetachedUnexpectedly: true

  storageMinimalAvailablePercentage: 10

  deletingConfirmationFlag: false

ingress:
  enabled: true
  ingressClassName: traefik
  host: longhorn.dharrsan.com
  tls: false
