apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Values.storage.persistence.claimName }}"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "{{ .Values.storage.persistence.size }}"
  storageClassName: "{{ .Values.storage.persistence.storageClass }}"
